### PR TITLE
King v1.2

### PR DESCRIPTION
**Pull request by climent**
Hi

I modified the PCB to use 4 cardinal points for DI and DO, so that one can select the direction of each of those. In other words: there are two 4-point crosses, one marked with DI and one with DO. On each PCB one can select the direction the Digital Input is coming from, and where the Digital Output is heading to, and solder the correct jumper to make it happen.

I reorganized the GND on the zones, so that it removes a bunch of the via holes, and cleaned the routes on the rest of the connections.

Let me know if you like this approach.

### CODE REVIEW

**Comment by climent** [comment]
Let me know if there is anything I can change/improve on the 1.2 branch, for this PR to be accepted.

**Comment by climent** [comment]
Also, here is a [render](https://i.imgur.com/nV6DiFlh.png) of a pre-released version of the PCB.

**Comment by RagingRoosevelt** [comment]
> Also, here is a [render](https://i.imgur.com/nV6DiFlh.png) of a pre-released version of the PCB.

Could you paste the rendered image into a comment on github?  The hosting on imgur seems to have broke.

**Comment by RagingRoosevelt** [comment]
I wonder if @JKing-B16 has seen this PR?

**Comment by JKing-B16** [comment]
Sorry, I had looked at this a while ago and thought I had answered all ready. I think the approach is really good and wish I had thought of it. I have merged it into my original branch.

**Pull request merged**
